# Copyright (C) 2009 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http:
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

#
# MODULE for NEON or NOT
#
# Support NEON
LOCAL_MODULE   := libffmpeg
# Not Supported NEON
#LOCAL_MODULE    := libffmpegv

LOCAL_MODULE_TAGS := optional


# Support NEON
ifeq ($(LOCAL_MODULE),libffmpeg)
LOCAL_CFLAGS := -DHAVE_AV_CONFIG_H -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DPIC -DCMP_HAVE_NEON -mfpu=neon -mfloat-abi=softfp -march=armv7-a -Wno-sign-compare -Wno-switch -Wno-pointer-sign
endif
# Support VFP
ifeq ($(LOCAL_MODULE),libffmpegv)
LOCAL_CFLAGS := -DHAVE_AV_CONFIG_H -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DPIC -marm -mfpu=vfp -mfloat-abi=softfp -march=armv7-a -Wno-sign-compare -Wno-switch -Wno-pointer-sign
endif


LOCAL_ARM_MODE := arm
#LOCAL_LDFLAGS := -L$(SYSROOT)/usr/lib -lz 

#LOCAL_LDFLAGS := -Wl,--no-warn-shared-textrel

# for jellybean 4.3 and above
# For supporting neon, armv7-a-neon must be set for TARGET_ARCH_VARIANT in BoardConfig.mk(i.e. build\target\board\generic\BoardConfig.mk)

LOCAL_SRC_FILES := \
libavutil/adler32.c   \
libavutil/aes.c \
libavutil/atomic.c \
libavutil/audio_fifo.c \
libavutil/avstring.c \
libavutil/base64.c \
libavutil/blowfish.c \
libavutil/bprint.c \
libavutil/buffer.c \
libavutil/cast5.c \
libavutil/camellia.c \
libavutil/channel_layout.c \
libavutil/color_utils.c \
libavutil/cpu.c \
libavutil/crc.c \
libavutil/des.c \
libavutil/dict.c \
libavutil/display.c \
libavutil/downmix_info.c \
libavutil/error.c \
libavutil/eval.c \
libavutil/fifo.c \
libavutil/file.c \
libavutil/file_open.c \
libavutil/fixed_dsp.c \
libavutil/float_dsp.c \
libavutil/opt.c \
libavutil/frame.c \
libavutil/hmac.c \
libavutil/imgutils.c \
libavutil/intmath.c \
libavutil/lfg.c \
libavutil/lls.c \
libavutil/log.c \
libavutil/log2_tab.c \
libavutil/lzo.c \
libavutil/mathematics.c \
libavutil/md5.c \
libavutil/pixdesc.c \
libavutil/random_seed.c \
libavutil/rational.c \
libavutil/rc4.c \
libavutil/reverse.c \
libavutil/sha.c \
libavutil/sha512.c \
libavutil/tea.c \
libavutil/tree.c \
libavutil/utils.c \
libavutil/mem.c \
libavutil/parseutils.c \
libavutil/samplefmt.c \
libavutil/stereo3d.c \
libavutil/time.c \
libavutil/timecode.c \
libavutil/xga_font_data.c \
libavutil/arm/cpu.c \
libavutil/arm/float_dsp_init_arm.c \
libavformat/4xm.c \
libavformat/aadec.c \
libavformat/aacdec.c \
libavformat/ac3dec.c \
libavformat/act.c \
libavformat/adp.c \
libavformat/adxdec.c \
libavformat/aea.c \
libavformat/aiffdec.c \
libavformat/allformats.c \
libavformat/amr.c \
libavformat/anm.c \
libavformat/apc.c \
libavformat/ape.c \
libavformat/apetag.c \
libavformat/apngdec.c \
libavformat/aqtitledec.c \
libavformat/asf.c \
libavformat/asfcrypt.c \
libavformat/asfdec_f.c \
libavformat/asfdec_o.c \
libavformat/assdec.c \
libavformat/ast.c \
libavformat/astdec.c \
libavformat/au.c \
libavformat/avc.c \
libavformat/avidec.c \
libavformat/avio.c \
libavformat/aviobuf.c \
libavformat/avlanguage.c \
libavformat/avr.c \
libavformat/avs.c \
libavformat/bethsoftvid.c \
libavformat/bintext.c \
libavformat/bit.c \
libavformat/bfi.c \
libavformat/bink.c \
libavformat/bmv.c \
libavformat/boadec.c \
libavformat/brstm.c \
libavformat/c93.c \
libavformat/caf.c \
libavformat/cafdec.c \
libavformat/cavsvideodec.c \
libavformat/cdg.c \
libavformat/cutils.c \
libavformat/dauddec.c \
libavformat/dfa.c \
libavformat/diracdec.c \
libavformat/dnxhddec.c \
libavformat/dsicin.c \
libavformat/dsfdec.c \
libavformat/dss.c \
libavformat/dtsdec.c \
libavformat/dtshddec.c \
libavformat/dump.c \
libavformat/dv.c \
libavformat/dvbsub.c \
libavformat/dxa.c \
libavformat/eacdata.c \
libavformat/epafdec.c \
libavformat/electronicarts.c \
libavformat/ffmdec.c \
libavformat/ffmetadec.c \
libavformat/file.c \
libavformat/filmstripdec.c \
libavformat/flacdec.c \
libavformat/flac_picture.c \
libavformat/flic.c \
libavformat/flvdec.c \
libavformat/frmdec.c \
libavformat/format.c \
libavformat/g722.c \
libavformat/g723_1.c \
libavformat/g729dec.c \
libavformat/gifdec.c \
libavformat/gsmdec.c \
libavformat/gxf.c \
libavformat/h261dec.c \
libavformat/h263dec.c \
libavformat/h264dec.c \
libavformat/hevc.c \
libavformat/hevcdec.c \
libavformat/hnm.c \
libavformat/id3v1.c \
libavformat/id3v2.c \
libavformat/idcin.c \
libavformat/idroqdec.c \
libavformat/iff.c \
libavformat/img2.c \
libavformat/img2dec.c \
libavformat/ingenientdec.c \
libavformat/ipmovie.c \
libavformat/isom.c \
libavformat/iss.c \
libavformat/iv8.c \
libavformat/lmlm4.c \
libavformat/matroska.c \
libavformat/matroskadec.c \
libavformat/metadata.c \
libavformat/microdvddec.c \
libavformat/m4vdec.c \
libavformat/mm.c \
libavformat/mmf.c \
libavformat/mov.c \
libavformat/mov_chan.c \
libavformat/mp3dec.c \
libavformat/mpeg.c \
libavformat/mpegts.c \
libavformat/mpegvideodec.c \
libavformat/msnwc_tcp.c \
libavformat/mtv.c \
libavformat/mux.c \
libavformat/mvi.c \
libavformat/mxf.c \
libavformat/mxfdec.c \
libavformat/ncdec.c \
libavformat/network.c \
libavformat/nsvdec.c \
libavformat/nut.c \
libavformat/nutdec.c \
libavformat/nuv.c \
libavformat/oggdec.c \
libavformat/oggparsecelt.c \
libavformat/oggparsedirac.c \
libavformat/oggparseflac.c \
libavformat/oggparseogm.c \
libavformat/oggparseopus.c \
libavformat/oggparseskeleton.c \
libavformat/oggparsespeex.c \
libavformat/oggparsetheora.c \
libavformat/oggparsevorbis.c \
libavformat/oggparsevp8.c \
libavformat/oma.c \
libavformat/omadec.c \
libavformat/options.c \
libavformat/os_support.c \
libavformat/pcm.c \
libavformat/pcmdec.c \
libavformat/psxstr.c \
libavformat/pva.c \
libavformat/qcp.c \
libavformat/r3d.c \
libavformat/rawdec.c \
libavformat/rawvideodec.c \
libavformat/replaygain.c \
libavformat/riff.c \
libavformat/riffdec.c \
libavformat/rl2.c \
libavformat/rm.c \
libavformat/rmdec.c \
libavformat/rmsipr.c \
libavformat/rpl.c \
libavformat/samidec.c \
libavformat/sauce.c \
libavformat/segafilm.c \
libavformat/sierravmd.c \
libavformat/siff.c \
libavformat/smacker.c \
libavformat/smjpeg.c \
libavformat/smjpegdec.c \
libavformat/sol.c \
libavformat/soxdec.c \
libavformat/subtitles.c \
libavformat/swf.c \
libavformat/swfdec.c \
libavformat/thp.c \
libavformat/tiertexseq.c \
libavformat/tmv.c \
libavformat/tta.c \
libavformat/txd.c \
libavformat/url.c \
libavformat/utils.c \
libavformat/vc1test.c \
libavformat/voc.c \
libavformat/vocdec.c \
libavformat/vorbiscomment.c \
libavformat/vplayerdec.c \
libavformat/vqf.c \
libavformat/w64.c \
libavformat/wavdec.c \
libavformat/wc3movie.c \
libavformat/westwood_aud.c \
libavformat/westwood_vqa.c \
libavformat/wv.c \
libavformat/wvdec.c \
libavformat/xa.c \
libavformat/yuv4mpegdec.c \
libavcodec/arm/aacpsdsp_init_arm.c \
libavcodec/arm/audiodsp_init_arm.c \
libavcodec/arm/ac3dsp_init_arm.c \
libavcodec/arm/ac3dsp_arm.S \
libavcodec/arm/blockdsp_init_arm.c \
libavcodec/arm/fft_fixed_init_arm.c \
libavcodec/arm/fft_init_arm.c \
libavcodec/arm/flacdsp_init_arm.c \
libavcodec/arm/flacdsp_arm.S \
libavcodec/arm/fmtconvert_init_arm.c \
libavcodec/arm/h264chroma_init_arm.c \
libavcodec/arm/h264dsp_init_arm.c \
libavcodec/arm/h264pred_init_arm.c \
libavcodec/arm/hevcdsp_init_arm.c \
libavcodec/arm/hpeldsp_init_arm.c \
libavcodec/arm/hpeldsp_arm.S \
libavcodec/arm/idctdsp_init_arm.c \
libavcodec/arm/idctdsp_arm.S \
libavcodec/arm/jrevdct_arm.S \
libavcodec/arm/mpegvideo_arm.c \
libavcodec/arm/mpegvideoencdsp_init_arm.c \
libavcodec/arm/mpegaudiodsp_init_arm.c \
libavcodec/arm/simple_idct_arm.S \
libavcodec/arm/sbrdsp_init_arm.c \
libavcodec/arm/rv34dsp_init_arm.c \
libavcodec/arm/vorbisdsp_init_arm.c \
libavcodec/4xm.c \
libavcodec/8bps.c \
libavcodec/8svx.c \
libavcodec/aacadtsdec.c \
libavcodec/aacdec.c \
libavcodec/aacdec_fixed.c \
libavcodec/aac_ac3_parser.c \
libavcodec/aac_adtstoasc_bsf.c \
libavcodec/aac_parser.c \
libavcodec/aacps_fixed.c \
libavcodec/aacps_float.c \
libavcodec/aacpsdsp_float.c \
libavcodec/aacpsdsp_fixed.c \
libavcodec/aacsbr.c \
libavcodec/aacsbr_fixed.c \
libavcodec/aactab.c \
libavcodec/aandcttab.c \
libavcodec/aasc.c \
libavcodec/ass.c \
libavcodec/eac3dec.c \
libavcodec/eac3_data.c \
libavcodec/ac3.c \
libavcodec/ac3_parser.c \
libavcodec/ac3dec.c \
libavcodec/ac3dec_fixed.c \
libavcodec/ac3dec_data.c \
libavcodec/ac3dec_float.c \
libavcodec/ac3dsp.c \
libavcodec/ac3tab.c \
libavcodec/acelp_filters.c \
libavcodec/acelp_pitch_delay.c \
libavcodec/acelp_vectors.c \
libavcodec/adpcm.c \
libavcodec/adpcm_data.c \
libavcodec/adx.c \
libavcodec/adxdec.c \
libavcodec/alac.c \
libavcodec/alac_data.c \
libavcodec/allcodecs.c \
libavcodec/alsdec.c \
libavcodec/amrnbdec.c \
libavcodec/amrwbdec.c \
libavcodec/anm.c \
libavcodec/apedec.c \
libavcodec/asv.c \
libavcodec/asvdec.c \
libavcodec/atrac.c \
libavcodec/atrac1.c \
libavcodec/atrac3.c \
libavcodec/atrac3plus.c \
libavcodec/atrac3plusdec.c \
libavcodec/atrac3plusdsp.c \
libavcodec/audioconvert.c \
libavcodec/audiodsp.c \
libavcodec/aura.c \
libavcodec/avfft.c \
libavcodec/avpacket.c \
libavcodec/avpicture.c \
libavcodec/avs.c \
libavcodec/bethsoftvideo.c \
libavcodec/bfi.c \
libavcodec/bgmc.c \
libavcodec/bink.c \
libavcodec/binkaudio.c \
libavcodec/binkdsp.c \
libavcodec/bitstream.c \
libavcodec/bitstream_filter.c \
libavcodec/blockdsp.c \
libavcodec/bmp.c \
libavcodec/bswapdsp.c \
libavcodec/c93.c \
libavcodec/cabac.c \
libavcodec/cavs.c \
libavcodec/cavs_parser.c \
libavcodec/cavsdata.c \
libavcodec/cavsdec.c \
libavcodec/cavsdsp.c \
libavcodec/cdgraphics.c \
libavcodec/celp_filters.c \
libavcodec/celp_math.c \
libavcodec/cga_data.c \
libavcodec/chomp_bsf.c \
libavcodec/cinepak.c \
libavcodec/cljrdec.c \
libavcodec/codec_desc.c \
libavcodec/cook.c \
libavcodec/cscd.c \
libavcodec/cyuv.c \
libavcodec/dca.c \
libavcodec/dcadec.c \
libavcodec/dcadata.c \
libavcodec/dcadsp.c \
libavcodec/dca_exss.c \
libavcodec/dca_parser.c \
libavcodec/dca_xll.c \
libavcodec/dct.c \
libavcodec/dct32_fixed.c \
libavcodec/dct32_float.c \
libavcodec/dirac.c \
libavcodec/dirac_arith.c \
libavcodec/diracdec.c \
libavcodec/diracdsp.c \
libavcodec/dirac_parser.c \
libavcodec/dnxhd_parser.c \
libavcodec/dnxhddata.c \
libavcodec/dnxhddec.c \
libavcodec/dpcm.c \
libavcodec/dpx.c \
libavcodec/dsicinaudio.c \
libavcodec/dsicinvideo.c \
libavcodec/dump_extradata_bsf.c \
libavcodec/dv.c \
libavcodec/dv_profile.c \
libavcodec/dvbsub_parser.c \
libavcodec/dvbsubdec.c \
libavcodec/dvdata.c \
libavcodec/dvdec.c \
libavcodec/dvdsub_parser.c \
libavcodec/dvdsubdec.c \
libavcodec/dirac_dwt.c \
libavcodec/dxa.c \
libavcodec/eacmv.c \
libavcodec/eaidct.c \
libavcodec/eamad.c \
libavcodec/eatgq.c \
libavcodec/eatgv.c \
libavcodec/eatqi.c \
libavcodec/error_resilience.c \
libavcodec/escape124.c \
libavcodec/escape130.c \
libavcodec/exif.c \
libavcodec/faanidct.c \
libavcodec/faxcompr.c \
libavcodec/fft_fixed.c \
libavcodec/fft_float.c \
libavcodec/fft_fixed_32.c \
libavcodec/fft_init_table.c \
libavcodec/ffv1.c \
libavcodec/flac.c \
libavcodec/flacdata.c \
libavcodec/flacdec.c \
libavcodec/flacdsp.c \
libavcodec/flashsv.c \
libavcodec/flicvideo.c \
libavcodec/flvdec.c \
libavcodec/fmtconvert.c\
libavcodec/fraps.c \
libavcodec/frwu.c \
libavcodec/g722.c \
libavcodec/g722dec.c \
libavcodec/g722dsp.c \
libavcodec/arm/g722dsp_init_arm.c \
libavcodec/g726.c \
libavcodec/gifdec.c \
libavcodec/golomb.c \
libavcodec/h261.c \
libavcodec/h261data.c \
libavcodec/h261_parser.c \
libavcodec/h261dec.c \
libavcodec/h263.c \
libavcodec/h263_parser.c \
libavcodec/h263data.c \
libavcodec/h263dec.c \
libavcodec/h263dsp.c \
libavcodec/h264.c \
libavcodec/h264_cabac.c \
libavcodec/h264_cavlc.c \
libavcodec/h264_direct.c \
libavcodec/h264_loopfilter.c \
libavcodec/h264_mb.c \
libavcodec/h264_mp4toannexb_bsf.c \
libavcodec/h264_parser.c \
libavcodec/h264_picture.c \
libavcodec/h264_ps.c \
libavcodec/h264_refs.c \
libavcodec/h264_sei.c \
libavcodec/h264_slice.c \
libavcodec/h264chroma.c \
libavcodec/h264dsp.c \
libavcodec/h264idct.c \
libavcodec/h264pred.c \
libavcodec/h264qpel.c \
libavcodec/arm/h264qpel_init_arm.c \
libavcodec/hevc.c \
libavcodec/hevc_cabac.c \
libavcodec/hevc_data.c \
libavcodec/hevc_filter.c \
libavcodec/hevc_mp4toannexb_bsf.c \
libavcodec/hevc_mvs.c \
libavcodec/hevc_parse.c \
libavcodec/hevc_parser.c \
libavcodec/hevc_ps.c \
libavcodec/hevc_refs.c \
libavcodec/hevc_sei.c \
libavcodec/hevcdsp.c \
libavcodec/hevcpred.c \
libavcodec/hpeldsp.c \
libavcodec/huffman.c \
libavcodec/huffyuv.c \
libavcodec/idcinvideo.c \
libavcodec/idctdsp.c \
libavcodec/iff.c \
libavcodec/imc.c \
libavcodec/imdct15.c \
libavcodec/imgconvert.c \
libavcodec/imx_dump_header_bsf.c \
libavcodec/indeo2.c \
libavcodec/indeo3.c \
libavcodec/indeo4.c \
libavcodec/indeo5.c \
libavcodec/intelh263dec.c \
libavcodec/interplayvideo.c \
libavcodec/intrax8.c \
libavcodec/intrax8dsp.c \
libavcodec/ituh263dec.c \
libavcodec/ivi.c \
libavcodec/ivi_dsp.c \
libavcodec/jpegls.c \
libavcodec/jpeglsdec.c \
libavcodec/jpegtables.c \
libavcodec/jrevdct.c \
libavcodec/kbdwin.c \
libavcodec/kgv1dec.c \
libavcodec/kmvc.c \
libavcodec/lcldec.c \
libavcodec/loco.c \
libavcodec/lossless_videodsp.c \
libavcodec/lossless_audiodsp.c \
libavcodec/arm/lossless_audiodsp_init_arm.c \
libavcodec/lsp.c \
libavcodec/lzw.c \
libavcodec/mace.c \
libavcodec/mathtables.c \
libavcodec/mdct_fixed.c \
libavcodec/mdct_float.c \
libavcodec/mdct_fixed_32.c \
libavcodec/mdec.c \
libavcodec/me_cmp.c \
libavcodec/arm/me_cmp_init_arm.c \
libavcodec/mimic.c \
libavcodec/mjpeg2jpeg_bsf.c \
libavcodec/mjpegdec.c \
libavcodec/mjpeg_parser.c \
libavcodec/mjpega_dump_header_bsf.c \
libavcodec/mjpegbdec.c \
libavcodec/mmvideo.c \
libavcodec/motionpixels.c \
libavcodec/movsub_bsf.c \
libavcodec/mp3_header_decompress_bsf.c \
libavcodec/mpeg_er.c \
libavcodec/mpeg12.c \
libavcodec/mpeg12dec.c \
libavcodec/mpeg12data.c \
libavcodec/mpeg4_unpack_bframes_bsf.c \
libavcodec/mpeg4audio.c \
libavcodec/mpeg4video.c \
libavcodec/mpeg4video_parser.c \
libavcodec/mpeg4videodec.c \
libavcodec/mpegaudio.c \
libavcodec/mpegaudiodsp.c \
libavcodec/mpegaudiodsp_data.c \
libavcodec/mpegaudiodsp_fixed.c \
libavcodec/mpegaudiodsp_float.c \
libavcodec/mpegaudio_parser.c \
libavcodec/mpegaudiodata.c \
libavcodec/mpegaudiodec_fixed.c \
libavcodec/mpegaudiodec_float.c \
libavcodec/mpegaudiodecheader.c \
libavcodec/mpegpicture.c \
libavcodec/mpegvideo.c \
libavcodec/mpegvideodsp.c \
libavcodec/mpegvideodata.c \
libavcodec/mpegvideoencdsp.c \
libavcodec/mpegvideo_motion.c \
libavcodec/mpegvideo_parser.c \
libavcodec/mpegutils.c \
libavcodec/msmpeg4.c \
libavcodec/msmpeg4data.c \
libavcodec/msmpeg4dec.c \
libavcodec/msrle.c \
libavcodec/msrledec.c \
libavcodec/msvideo1.c \
libavcodec/nellymoser.c \
libavcodec/nellymoserdec.c \
libavcodec/noise_bsf.c \
libavcodec/nuv.c \
libavcodec/options.c \
libavcodec/parser.c \
libavcodec/pcm-bluray.c \
libavcodec/pcm-dvd.c \
libavcodec/pcm.c \
libavcodec/pcx.c \
libavcodec/pgssubdec.c \
libavcodec/png.c \
libavcodec/pngdec.c \
libavcodec/pngdsp.c \
libavcodec/pnm.c \
libavcodec/pnm_parser.c \
libavcodec/pnmdec.c \
libavcodec/ptx.c \
libavcodec/qcelpdec.c \
libavcodec/qdrw.c \
libavcodec/qpeg.c \
libavcodec/qpeldsp.c \
libavcodec/qtrle.c \
libavcodec/r210dec.c \
libavcodec/ra144.c \
libavcodec/ra288.c \
libavcodec/rangecoder.c \
libavcodec/raw.c \
libavcodec/rawdec.c \
libavcodec/rdft.c \
libavcodec/remove_extradata_bsf.c \
libavcodec/resample.c \
libavcodec/resample2.c \
libavcodec/rl.c \
libavcodec/rl2.c \
libavcodec/roqvideo.c \
libavcodec/roqvideodec.c \
libavcodec/rpza.c \
libavcodec/rtjpeg.c \
libavcodec/rv10.c \
libavcodec/rv30.c \
libavcodec/rv34.c \
libavcodec/rv30dsp.c \
libavcodec/rv34dsp.c \
libavcodec/rv40.c \
libavcodec/rv40dsp.c \
libavcodec/arm/rv40dsp_init_arm.c \
libavcodec/samidec.c \
libavcodec/sbrdsp.c \
libavcodec/sbrdsp_fixed.c \
libavcodec/sgidec.c \
libavcodec/shorten.c \
libavcodec/simple_idct.c \
libavcodec/sinewin.c \
libavcodec/sinewin_fixed.c \
libavcodec/sipr.c \
libavcodec/sipr16k.c \
libavcodec/smacker.c \
libavcodec/smc.c \
libavcodec/sonic.c \
libavcodec/sp5xdec.c \
libavcodec/sunrast.c \
libavcodec/startcode.c \
libavcodec/svq1.c \
libavcodec/svq1dec.c \
libavcodec/svq13.c \
libavcodec/svq3.c \
libavcodec/synth_filter.c \
libavcodec/targa.c \
libavcodec/textdec.c \
libavcodec/texturedsp.c \
libavcodec/tiertexseqv.c \
libavcodec/tiff.c \
libavcodec/tiff_common.c \
libavcodec/tiff_data.c \
libavcodec/tmv.c \
libavcodec/tpeldsp.c \
libavcodec/truemotion1.c \
libavcodec/truemotion2.c \
libavcodec/truespeech.c \
libavcodec/tscc.c \
libavcodec/tscc2.c \
libavcodec/tta.c \
libavcodec/ttadata.c \
libavcodec/ttadsp.c \
libavcodec/twinvq.c \
libavcodec/txd.c \
libavcodec/ulti.c \
libavcodec/utils.c \
libavcodec/v210dec.c \
libavcodec/v210x.c \
libavcodec/vb.c \
libavcodec/vc1.c \
libavcodec/vc1_block.c \
libavcodec/vc1_loopfilter.c \
libavcodec/vc1_mc.c \
libavcodec/vc1_pred.c \
libavcodec/vc1_parser.c \
libavcodec/vc1data.c \
libavcodec/vc1dec.c \
libavcodec/vc1dsp.c \
libavcodec/arm/vc1dsp_init_arm.c \
libavcodec/vcr1.c \
libavcodec/videodsp.c \
libavcodec/arm/videodsp_init_arm.c \
libavcodec/vmdaudio.c \
libavcodec/vmdvideo.c \
libavcodec/vmnc.c \
libavcodec/vorbis.c \
libavcodec/vorbis_data.c \
libavcodec/vorbis_parser.c \
libavcodec/vorbisdsp.c \
libavcodec/vorbisdec.c \
libavcodec/vp3.c \
libavcodec/vp3_parser.c \
libavcodec/vp3dsp.c \
libavcodec/arm/vp3dsp_init_arm.c \
libavcodec/vp5.c \
libavcodec/vp56.c \
libavcodec/vp56data.c \
libavcodec/vp56dsp.c \
libavcodec/vp56rac.c \
libavcodec/vp6.c \
libavcodec/vp6dsp.c \
libavcodec/arm/vp6dsp_init_arm.c \
libavcodec/vqavideo.c \
libavcodec/wavpack.c \
libavcodec/wma.c \
libavcodec/wma_common.c \
libavcodec/wma_freqs.c \
libavcodec/wmadec.c \
libavcodec/wmalosslessdec.c \
libavcodec/wmaprodec.c \
libavcodec/wmavoice.c \
libavcodec/wmv2.c \
libavcodec/wmv2dec.c \
libavcodec/wmv2dsp.c \
libavcodec/wnv1.c \
libavcodec/ws-snd1.c \
libavcodec/xan.c \
libavcodec/xiph.c \
libavcodec/xl.c \
libavcodec/xsubdec.c \
libavcodec/xvididct.c \
libavcodec/zmbv.c \
libavcodec/pthread.c \
libavcodec/pthread_frame.c \
libavcodec/pthread_slice.c \
libswresample/audioconvert.c \
libswresample/dither.c \
libswresample/options.c \
libswresample/rematrix.c \
libswresample/resample.c \
libswresample/resample_dsp.c \
libswresample/swresample.c \
libswresample/swresample_frame.c \

VFP_SRC_FILES := \
libavcodec/arm/dcadsp_init_arm.c \
libavcodec/arm/fmtconvert_vfp.S \
libavcodec/arm/fft_vfp.S \
libavcodec/arm/mdct_vfp.S \
libavutil/arm/float_dsp_init_vfp.c \
libavutil/arm/float_dsp_vfp.S \

ARM6_SRC_FILES := \
libavcodec/arm/ac3dsp_armv6.S \
libavcodec/arm/hpeldsp_armv6.S \
libavcodec/arm/hpeldsp_init_armv6.c \
libavcodec/arm/idctdsp_init_armv6.c \
libavcodec/arm/idctdsp_armv6.S \
libavcodec/arm/me_cmp_armv6.S \
libavcodec/arm/mpegvideo_armv5te.c \
libavcodec/arm/mpegvideo_armv5te_s.S \
libavcodec/arm/mpegvideoencdsp_armv6.S \
libavcodec/arm/mpegaudiodsp_fixed_armv6.S \
libavcodec/arm/simple_idct_armv6.S \
libavcodec/arm/startcode_armv6.S \

NEON_SRC_FILES := \
libavutil/arm/float_dsp_init_neon.c \
libavutil/arm/float_dsp_neon.S \
libavcodec/arm/ac3dsp_neon.S \
libavcodec/arm/aacpsdsp_neon.S \
libavcodec/arm/audiodsp_init_neon.c \
libavcodec/arm/audiodsp_neon.S \
libavcodec/arm/blockdsp_init_neon.c \
libavcodec/arm/blockdsp_neon.S \
libavcodec/arm/dcadsp_neon.S \
libavcodec/arm/fft_neon.S \
libavcodec/arm/fft_fixed_neon.S \
libavcodec/arm/fmtconvert_neon.S \
libavcodec/arm/g722dsp_neon.S \
libavcodec/arm/h264cmc_neon.S \
libavcodec/arm/h264dsp_neon.S \
libavcodec/arm/h264idct_neon.S \
libavcodec/arm/h264pred_neon.S \
libavcodec/arm/h264qpel_neon.S \
libavcodec/arm/hevcdsp_deblock_neon.S \
libavcodec/arm/hevcdsp_idct_neon.S \
libavcodec/arm/hevcdsp_init_neon.c \
libavcodec/arm/hevcdsp_qpel_neon.S \
libavcodec/arm/hpeldsp_init_neon.c \
libavcodec/arm/hpeldsp_neon.S \
libavcodec/arm/int_neon.S \
libavcodec/arm/idctdsp_init_neon.c \
libavcodec/arm/idctdsp_neon.S \
libavcodec/arm/lossless_audiodsp_neon.S \
libavcodec/arm/mdct_neon.S \
libavcodec/arm/mdct_fixed_neon.S \
libavcodec/arm/mpegvideo_neon.S \
libavcodec/arm/rdft_neon.S \
libavcodec/arm/rv34dsp_neon.S \
libavcodec/arm/rv40dsp_neon.S \
libavcodec/arm/sbrdsp_neon.S \
libavcodec/arm/synth_filter_neon.S \
libavcodec/arm/simple_idct_neon.S \
libavcodec/arm/vc1dsp_init_neon.c \
libavcodec/arm/vc1dsp_neon.S \
libavcodec/arm/vorbisdsp_neon.S \
libavcodec/arm/vp3dsp_neon.S \
libavcodec/arm/vp6dsp_neon.S \

# Support NEON
ifeq ($(LOCAL_MODULE),libffmpeg)
LOCAL_SRC_FILES +=$(NEON_SRC_FILES)
endif
# Support VFP
ifeq ($(LOCAL_MODULE),libffmpegv)
LOCAL_SRC_FILES +=$(VFP_SRC_FILES)
LOCAL_SRC_FILES +=$(ARM6_SRC_FILES)
endif


LOCAL_LDLIBS      := -lz
LOCAL_C_INCLUDES += external/zlib $(LOCAL_PATH)/../librdns

LOCAL_SHARED_LIBRARIES := \
libcutils \
libutils \
libz \

LOCAL_PRELINK_MODULE := false
include $(BUILD_SHARED_LIBRARY)


